<?php
class BillController extends Controller {
 public function index(): void { $cid=$this->companyId(); $s=$this->db->prepare('SELECT b.*, v.name vendor_name FROM bills b JOIN vendors v ON v.id=b.vendor_id WHERE b.company_id=? ORDER BY b.bill_date DESC'); $s->execute([$cid]); $bills=$s->fetchAll(); $this->render('bills/index', compact('bills')); }
 public function create(): void { $cid=$this->companyId(); $vendors=$this->list('vendors',$cid); $expenses=$this->accounts($cid,'expense'); $bill=null; $this->render('bills/form', compact('vendors','expenses','bill')); }
 public function edit(): void { $cid=$this->companyId(); $bill=$this->load((int)($_GET['id']??0)); $vendors=$this->list('vendors',$cid); $expenses=$this->accounts($cid,'expense'); $expenseAccountId=$this->sourceAccountId($cid,'bill',(int)$bill['id'],'debit'); $this->render('bills/form', compact('vendors','expenses','bill','expenseAccountId')); }
 public function save(): void { $this->persist(false); }
 public function update(): void { $this->persist(true); }
 public function delete(): void { check_csrf(); $cid=$this->companyId(); $id=(int)($_POST['id']??0); $this->db->beginTransaction(); try { $this->db->prepare('DELETE FROM bills WHERE id=? AND company_id=?')->execute([$id,$cid]); Ledger::deleteBySource($this->db,$cid,'bill',$id); Ledger::deleteBySource($this->db,$cid,'bill_payment',$id); $this->db->commit(); $this->redirect('bills'); } catch(Throwable $e){ $this->db->rollBack(); die($e->getMessage()); } }
 public function pay(): void { check_csrf(); $cid=$this->companyId(); $id=(int)$_POST['id']; $amt=(float)$_POST['amount']; $date=$_POST['payment_date']; $this->db->beginTransaction(); try { Ledger::post($this->db,$cid,$date,'Bill payment', [['account_id'=>$this->acct($cid,'Accounts Payable'),'debit'=>$amt],['account_id'=>$this->acct($cid,'Checking'),'credit'=>$amt]],'bill_payment',$id); $this->updateBillStatus($cid,$id); $this->db->commit(); $this->redirect('bills'); } catch(Exception $e){ $this->db->rollBack(); die($e->getMessage()); }}
 private function persist(bool $edit): void { check_csrf(); $cid=$this->companyId(); $total=(float)$_POST['total']; if($total<0) die('Total cannot be negative.'); $this->db->beginTransaction(); try { if($edit){ $id=(int)$_POST['id']; $this->db->prepare('UPDATE bills SET vendor_id=?, bill_number=?, bill_date=?, due_date=?, total=?, notes=? WHERE id=? AND company_id=?')->execute([$_POST['vendor_id'],$_POST['bill_number'],$_POST['bill_date'],$_POST['due_date'],$total,$_POST['notes']??'', $id,$cid]); Ledger::deleteBySource($this->db,$cid,'bill',$id); } else { $s=$this->db->prepare('INSERT INTO bills(company_id,vendor_id,bill_number,bill_date,due_date,total,status,notes) VALUES(?,?,?,?,?,?,?,?)'); $s->execute([$cid,$_POST['vendor_id'],$_POST['bill_number'],$_POST['bill_date'],$_POST['due_date'],$total,'open',$_POST['notes']??'']); $id=(int)$this->db->lastInsertId(); } Ledger::post($this->db,$cid,$_POST['bill_date'],'Bill '.$_POST['bill_number'],[['account_id'=>(int)$_POST['expense_account_id'],'debit'=>$total],['account_id'=>$this->acct($cid,'Accounts Payable'),'credit'=>$total]],'bill',$id); $this->updateBillStatus($cid,$id); $this->db->commit(); $this->redirect('bills'); } catch(Exception $e){ $this->db->rollBack(); die($e->getMessage()); }}
 private function updateBillStatus($cid,$id): void { $s=$this->db->prepare('SELECT total FROM bills WHERE id=? AND company_id=?'); $s->execute([$id,$cid]); $bill=$s->fetch(); if(!$bill)return; $p=$this->db->prepare("SELECT COALESCE(SUM(jl.debit),0) paid FROM journal_lines jl JOIN journal_entries je ON je.id=jl.journal_entry_id JOIN accounts a ON a.id=jl.account_id WHERE je.company_id=? AND je.source_type='bill_payment' AND je.source_id=? AND a.name='Accounts Payable'"); $p->execute([$cid,$id]); $paid=(float)$p->fetch()['paid']; $status=$paid>=(float)$bill['total']?'paid':'open'; $this->db->prepare('UPDATE bills SET status=? WHERE id=? AND company_id=?')->execute([$status,$id,$cid]); }
 private function load($id){ $cid=$this->companyId(); $s=$this->db->prepare('SELECT * FROM bills WHERE id=? AND company_id=?'); $s->execute([$id,$cid]); $row=$s->fetch(); if(!$row)die('Bill not found'); return $row; }
 private function sourceAccountId($cid,$type,$id,$side){ $col=$side==='credit'?'jl.credit':'jl.debit'; $s=$this->db->prepare("SELECT jl.account_id FROM journal_lines jl JOIN journal_entries je ON je.id=jl.journal_entry_id WHERE je.company_id=? AND je.source_type=? AND je.source_id=? AND $col > 0 LIMIT 1"); $s->execute([$cid,$type,$id]); $r=$s->fetch(); return $r?(int)$r['account_id']:null; }
 private function list($t,$cid){$s=$this->db->prepare("SELECT * FROM $t WHERE company_id=? ORDER BY name");$s->execute([$cid]);return $s->fetchAll();}
 private function accounts($cid,$type){$s=$this->db->prepare('SELECT * FROM accounts WHERE company_id=? AND type=? ORDER BY code');$s->execute([$cid,$type]);return $s->fetchAll();}
 private function acct($cid,$name){$s=$this->db->prepare('SELECT id FROM accounts WHERE company_id=? AND name=?');$s->execute([$cid,$name]);$r=$s->fetch(); if(!$r) throw new Exception('Missing required account: '.$name); return (int)$r['id'];}
}
