<?php
class InvoiceController extends Controller {
 public function index(): void { $cid=$this->companyId(); $s=$this->db->prepare('SELECT i.*, c.name customer_name, COALESCE(p.paid_amount,0) paid_amount, COALESCE(p.payment_count,0) payment_count FROM invoices i JOIN customers c ON c.id=i.customer_id LEFT JOIN (SELECT invoice_id, company_id, SUM(amount) paid_amount, COUNT(*) payment_count FROM payments GROUP BY invoice_id, company_id) p ON p.invoice_id=i.id AND p.company_id=i.company_id WHERE i.company_id=? ORDER BY i.invoice_date DESC'); $s->execute([$cid]); $invoices=$s->fetchAll(); $this->render('invoices/index', compact('invoices')); }
 public function create(): void { $cid=$this->companyId(); $customers=$this->list('customers',$cid); $income=$this->accounts($cid,'income'); $invoice=null; $this->render('invoices/form', compact('customers','income','invoice')); }
 public function edit(): void { $cid=$this->companyId(); $invoice=$this->load((int)($_GET['id']??0)); if($this->hasPayments($cid,(int)$invoice['id'])) die('This invoice already has a payment recorded, so it cannot be edited. Delete the invoice if you need to remove both the invoice and its payment.'); $customers=$this->list('customers',$cid); $income=$this->accounts($cid,'income'); $incomeAccountId=$this->sourceAccountId($cid,'invoice',(int)$invoice['id'],'credit'); $this->render('invoices/form', compact('customers','income','invoice','incomeAccountId')); }
 public function save(): void { $this->persist(false); }
 public function update(): void { $this->persist(true); }
 public function delete(): void { check_csrf(); $cid=$this->companyId(); $id=(int)($_POST['id']??0); $this->db->beginTransaction(); try { Ledger::deleteBySource($this->db,$cid,'invoice_payment',$id); $this->db->prepare('DELETE FROM payments WHERE invoice_id=? AND company_id=?')->execute([$id,$cid]); Ledger::deleteBySource($this->db,$cid,'invoice',$id); $this->db->prepare('DELETE FROM invoices WHERE id=? AND company_id=?')->execute([$id,$cid]); $this->db->commit(); $this->redirect('invoices'); } catch(Throwable $e){ $this->db->rollBack(); die($e->getMessage()); } }
 public function pay(): void { check_csrf(); $cid=$this->companyId(); $id=(int)$_POST['id']; $amt=(float)$_POST['amount']; $date=$_POST['payment_date']; $invoice=$this->load($id); if($this->hasPayments($cid,$id) || $invoice['status']==='paid') die('A payment has already been recorded for this invoice. Delete the invoice if you need to remove both the invoice and its payment.'); if($amt<=0) die('Payment amount must be greater than zero.'); if($amt>(float)$invoice['total']) die('Payment amount cannot be greater than the invoice total.'); $this->db->beginTransaction(); try { $this->db->prepare('INSERT INTO payments(company_id,invoice_id,payment_date,amount) VALUES(?,?,?,?)')->execute([$cid,$id,$date,$amt]); Ledger::post($this->db,$cid,$date,'Invoice payment', [['account_id'=>$this->acct($cid,'Checking'),'debit'=>$amt],['account_id'=>$this->acct($cid,'Accounts Receivable'),'credit'=>$amt]],'invoice_payment',$id); $this->updateInvoiceStatus($cid,$id); $this->db->commit(); $this->redirect('invoices'); } catch(Exception $e){ $this->db->rollBack(); die($e->getMessage()); }}
 private function persist(bool $edit): void { check_csrf(); $cid=$this->companyId(); $total=(float)$_POST['total']; if($total<0) die('Total cannot be negative.'); $this->db->beginTransaction(); try { if($edit){ $id=(int)$_POST['id']; if($this->hasPayments($cid,$id)) throw new Exception('This invoice already has a payment recorded, so it cannot be edited. Delete the invoice if you need to remove both the invoice and its payment.'); $this->db->prepare('UPDATE invoices SET customer_id=?, invoice_number=?, invoice_date=?, due_date=?, total=?, notes=? WHERE id=? AND company_id=?')->execute([$_POST['customer_id'],$_POST['invoice_number'],$_POST['invoice_date'],$_POST['due_date'],$total,$_POST['notes']??'', $id,$cid]); Ledger::deleteBySource($this->db,$cid,'invoice',$id); } else { $s=$this->db->prepare('INSERT INTO invoices(company_id,customer_id,invoice_number,invoice_date,due_date,total,status,notes) VALUES(?,?,?,?,?,?,?,?)'); $s->execute([$cid,$_POST['customer_id'],$_POST['invoice_number'],$_POST['invoice_date'],$_POST['due_date'],$total,'open',$_POST['notes']??'']); $id=(int)$this->db->lastInsertId(); } Ledger::post($this->db,$cid,$_POST['invoice_date'],'Invoice '.$_POST['invoice_number'],[['account_id'=>$this->acct($cid,'Accounts Receivable'),'debit'=>$total],['account_id'=>(int)$_POST['income_account_id'],'credit'=>$total]],'invoice',$id); $this->updateInvoiceStatus($cid,$id); $this->db->commit(); $this->redirect('invoices'); } catch(Exception $e){ $this->db->rollBack(); die($e->getMessage()); }}
 private function updateInvoiceStatus($cid,$id): void { $s=$this->db->prepare('SELECT total FROM invoices WHERE id=? AND company_id=?'); $s->execute([$id,$cid]); $inv=$s->fetch(); if(!$inv)return; $p=$this->db->prepare('SELECT COALESCE(SUM(amount),0) paid FROM payments WHERE invoice_id=? AND company_id=?'); $p->execute([$id,$cid]); $paid=(float)$p->fetch()['paid']; $status=$paid>=(float)$inv['total']?'paid':'open'; $this->db->prepare('UPDATE invoices SET status=? WHERE id=? AND company_id=?')->execute([$status,$id,$cid]); }
 private function hasPayments($cid,$id): bool { $s=$this->db->prepare('SELECT COUNT(*) c FROM payments WHERE invoice_id=? AND company_id=?'); $s->execute([$id,$cid]); return (int)$s->fetch()['c'] > 0; }
 private function load($id){ $cid=$this->companyId(); $s=$this->db->prepare('SELECT * FROM invoices WHERE id=? AND company_id=?'); $s->execute([$id,$cid]); $row=$s->fetch(); if(!$row)die('Invoice not found'); return $row; }
 private function sourceAccountId($cid,$type,$id,$side){ $col=$side==='credit'?'jl.credit':'jl.debit'; $s=$this->db->prepare("SELECT jl.account_id FROM journal_lines jl JOIN journal_entries je ON je.id=jl.journal_entry_id WHERE je.company_id=? AND je.source_type=? AND je.source_id=? AND $col > 0 LIMIT 1"); $s->execute([$cid,$type,$id]); $r=$s->fetch(); return $r?(int)$r['account_id']:null; }
 private function list($t,$cid){$s=$this->db->prepare("SELECT * FROM $t WHERE company_id=? ORDER BY name");$s->execute([$cid]);return $s->fetchAll();}
 private function accounts($cid,$type){$s=$this->db->prepare('SELECT * FROM accounts WHERE company_id=? AND type=? ORDER BY code');$s->execute([$cid,$type]);return $s->fetchAll();}
 private function acct($cid,$name){$s=$this->db->prepare('SELECT id FROM accounts WHERE company_id=? AND name=?');$s->execute([$cid,$name]);$r=$s->fetch(); if(!$r) throw new Exception('Missing required account: '.$name); return (int)$r['id'];}
}
